### ISSUE TITLE
Pagination Refactoring

### ISSUE THREAD

**Issue by A** [A/client-rest-framework#3]
Currently, pagination is soldered in API/Repository classes, therefore backend must have `PageNumberPagination` enabled. The goal is to implement mechanic to set optional `pagination` class for `APIRepository` and process list response via the pagination class.

Pagination may just proxy results and wrap `T[]` typings into corresponding data shape, or may provide additional calculated data, such as `page`, `pages`, `size`, to simplify user code.

Example of pagination results generic used in userland:

```
interface Paginated<T> {
  count: number
  page: number;
  size: number;
  items: T[];
}
```

Types of Pagination:
- `LimitOfsetPagination`
- `PageNumberPagination`

Pagination Options
- page
- size
- queryParamKey

Example of current pagination:

```
    const page = await repos.sites.list(this.page, {
     // internal details of pagination are exposed to the end user, what's wrong
      queryParams: {
        page: this.page,
        page_size: this.pageSize,
      }
    });
```

## TODO

- [ ] Remove DTO From model serializer, it's not used
- [ ] Remove DTO From APIRepository
- [ ] Add DTO to RESTAPI class
- [ ] Make Pagination accept Domain Model type from serializer explicitly (seems like TS limitation, no way to pass generic as a type parameter)

**Comment by A** [comment]
Example Implementation:

```typescript
const item = { createdAt: "2022-01-01" }

interface ISerializer {
    fromDTO(data: any): any
}

interface IAPI {
    list(): any
}

class APIRepository {
    api: IAPI
    serializer: ISerializer

    list() {
        type SerializedItem = ReturnType<this['serializer']['fromDTO']>
        const { items, ...meta } = this.api.list() as ReturnType<this['api']['list']>
        const serializedItems = items.map(this.serializer.fromDTO) as SerializedItem[]
        return [serializedItems, meta] as [SerializedItem[], typeof meta]
    }
}

class DRFPagination<DTO> {
    cast(data: any) {
        return data as { items: DTO[], count: number };
    }
}

class NoPagination<DTO> {
    cast(data: any) {
        return { items: data as DTO[] };
    }
}

interface IPagination {
    cast<T>(data: any): any
}

class BaseAPI<DTO> {
    pagination: IPagination

    list() {
        type PaginatedAPIResponse = ReturnType<this['pagination']['cast']>
        const response = [item]
        return this.pagination.cast<DTO>(response) as PaginatedAPIResponse;
    }
}

class API<DTO> extends BaseAPI<DTO> {
    // pagination = new NoPagination<DTO>()
    pagination = new DRFPagination<DTO>()
}

class Serializer  {
    fromDTO(data: { [k: string]: any }) { return ({ createdAt: new Date(data.createdAt) }) }
}

class RealAPIRepository extends APIRepository {
    api = new API<ItemDTO>()
    serializer = new Serializer()
}

type SerializedItem = ReturnType<typeof realAPIRepository.serializer.fromDTO>

const realAPIRepository = new RealAPIRepository()
const apiListResponse = realAPIRepository.api.list()
const serializedListResponse = apiListResponse.items.map(realAPIRepository.serializer.fromDTO)
const [data, meta] = realAPIRepository.list()
data[0].createdAt;


interface ItemDTO {
    createdAt: string;
}
```
